#!/bin/bash

# Usage:
#
# createElastixWebsite <action>
#
# with
# <action> one of:
#   exportwin
#   exportlinux64
#   exportlinux32 (only on rashindra's computer)
#   doxygen
#   ziplinux64
#   ziplinux32 (only on rashindra's computer)
#   zipwin
#   collect
#
# Typical use:
# 1. Prepare a release tag
# 2. Set the version and tag variables in this script
# 3. call this script with argument exportwin
# 4. call this script with argument exportlinux64
# 5. Run cmake on windows and linux.
# 6. run make install on linux
# 7. compile and install on windows using vc2008.
# 8. create the manual on windows, using latex.
# 9. call this script with argument doxygen
# 10. call this script with argument zipwin
# 11. call this script with argument ziplinux64
# 12. call this script with argument collect
# 13. log in on rashindra's computer, using ssh
# 14. call this script with argument exportlinux32
# 15. run cmake, and make install
# 16. call this script with argument ziplinux32
# 17. copy the resulting zip manually using winscp to $tempdir/downloads
# 18. copy $tempdir to the website, using winscp.
#
# This script is rather nongeneric. It only works on stefan's computer :)
#
#

arg="$1"

# You have to set the following
version="4.3"
tag="elastix_04_3"

username="sklein"

# Some base directories
exportbasedirwin="d:/tk/elastix/exports"
exportbasedirlinux64="m:/tk/elastix/exports"
# when using rashindra's machine:
exportbasedirlinux32="/home/stefan/tk/elastix/exports"
# when using the biggrid
exportbasedirlinux32grid="m:/tk/elastix/exports"
exportdirwin="$exportbasedirwin/tags/$tag"
exportdirlinux64="$exportbasedirlinux64/tags/$tag"
# when using rashindra's computer:
exportdirlinux32="$exportbasedirlinux32/tags/$tag"
# when using the biggrid
exportdirlinux32grid="$exportbasedirlinux32grid/tags/$tag""linux32"
svnurl="https://svn.bigr.nl/elastix"
tempdir="d:/dox/elastixwebsite/$tag"
websitebase="http://elastix.isi.uu.nl"
copyright="$exportdirwin/src/CopyrightElastix.txt"

# The stuff we do not want to distribute
leaveouts="src/Components/ImageSamplers/ReducedDimensionGrid src/Components/Metrics/AdvancedRigidityPenalty src/Components/Metrics/VarianceOverLastDimension src/Components/Metrics/ZeroDeformationConstraint src/Components/Optimizers/FullSearch2 src/Components/Optimizers/PreconditionedGradientDescent src/Components/Transforms/CyclicBSplineTransform src/Testing"

# checkout linux64 export:
if [ "$arg" = "exportlinux64" ]
then
  svn export --force --native-eol LF $svnurl/tags/$tag $exportdirlinux64
  for leaveout in $leaveouts
  do
    rm -r $exportdirlinux64/$leaveout
  done
  mkdir -p $exportdirlinux64/install
  mkdir -p $exportdirlinux64/release
  mkdir -p $exportdirlinux64/help
  exit
fi

# checkout linux32 export; Run this one directly on rashindra's computer!
if [ "$arg" = "exportlinux32" ]
then
  svn export --native-eol LF $svnurl/tags/$tag $exportdirlinux32
  for leaveout in $leaveouts
  do
    rm -r $exportdirlinux32/$leaveout
  done
  mkdir -p $exportdirlinux32/install
  mkdir -p $exportdirlinux32/release
  mkdir -p $exportdirlinux32/help
  exit
fi

# checkout windows export:
if [ "$arg" = "exportwin" ]
then
  svn export --native-eol CRLF $svnurl/tags/$tag $exportdirwin
  for leaveout in $leaveouts
  do
    rm -r $exportdirwin/$leaveout
  done
  mkdir -p $exportdirwin/install
  mkdir -p $exportdirwin/bin
  mkdir -p $exportdirwin/help
  exit
fi

if [ "$arg" = "doxygen" ]
then
  # Create html help
  currentdir=`pwd`
  cd $exportdirwin/help
  doxygen doxyfile.out &> doxygen.log
  cd $currentdir
  exit
fi

# zip linux64
if [ "$arg" = "ziplinux64" ]
then
  currentdir=`pwd`
  cd $exportdirlinux64
  # tar does not recognise m:/... filenames; convert to cygwin style.
  cwdir=`pwd`
  # select which documentation to include in the source zip/tar
  doxfordistribution=`find dox -type f | grep -v "dox/manual" | grep -v "dox/createWebsite"`
  tar -cjvf $cwdir/elastix_sources_v$version.tar.bz2 src $doxfordistribution
  cd install
  cp ../src/CopyrightElastix.txt .
  tar -cjvf $cwdir/elastix_linux64_v$version.tar.bz2 *
  cd ../help
  tar -cjvf $cwdir/elastix_example_v$version.tar.bz2 exampleinput example
  cd $currentdir
  exit
fi

# zip linux32grid
if [ "$arg" = "ziplinux32grid" ]
then
  currentdir=`pwd`
  cd $exportdirlinux32grid
  # tar does not recognise m:/... filenames; convert to cygwin style.
  cwdir=`pwd`
  # select which documentation to include in the source zip/tar
  doxfordistribution=`find dox -type f | grep -v "dox/manual" | grep -v "dox/createWebsite"`
  cd install
  cp ../src/CopyrightElastix.txt .
  tar -cjvf $cwdir/elastix_linux32_v$version.tar.bz2 *
  cd $currentdir
  exit
fi

# zip linux32: run this one directly on rashindra's computer
if [ "$arg" = "ziplinux32" ]
then
  # zip only binaries
  currentdir=`pwd`
  cd $exportdirlinux32
  cwdir=`pwd`
  cd install
  cp ../src/CopyrightElastix.txt .
  tar -cjvf $cwdir/elastix_linux32_v$version.tar.bz2 *
  cd $currentdir
  exit
fi

# zip win
if [ "$arg" = "zipwin" ]
then
  currentdir=`pwd`
  cd $exportdirwin
  rm elastix*.zip
  doxfordistribution=`find dox -type f | grep -v "dox/manual" | grep -v "dox/createWebsite"`
  wzzip -ex -a -P $exportdirwin/elastix_sources_v$version.zip $doxfordistribution
  wzzip -ex -a -r -P $exportdirwin/elastix_sources_v$version.zip src
  cd install
  cp ../src/CopyrightElastix.txt .
	cp d:/tk/install/libtiff3.dll .
	cp d:/tk/install/jpeg62.dll .
	cp d:/tk/install/zlib1.dll .
  wzzip -ex -a -r -P $exportdirwin/elastix_windows32_v$version.zip *
  cd ../help
  wzzip -ex -a -r -P $exportdirwin/elastix_example_v$version.zip exampleinput example.bat
  cd $currentdir
  exit
fi

# collect all stuff that needs to be copied to the website
if [ "$arg" = "collect" ]
then
  rm -r $tempdir
  mkdir -p $tempdir
  mkdir -p $tempdir/download
  cp $exportdirwin/*.zip $tempdir/download
  cp $exportdirlinux64/*.tar.bz2 $tempdir/download
#  cp $exportdirlinux32grid/*.tar.bz2 $tempdir/download
  cp $exportdirwin/dox/manual/manual.pdf $tempdir/download/elastix_manual_v$version.pdf
  cp -r $exportdirwin/help/html $tempdir/doxygen

  # Create a version.txt file with the version number in it.
  echo "v"$version > $tempdir/download/version.txt

  # write the date/time
  date '+%d-%m-%Y' > $tempdir/download/latestreleasedate.txt

  # copy the copyright message
  cp $exportdirwin/src/CopyrightElastix.txt $tempdir

  # copy the linux32 binaries manually using winscp
  exit
fi

# copy using winscp

exit 0

