[project]
name = "elastix"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "win-64", "osx-64", "osx-arm64"]

[tasks]
clean = { cmd = "git clean -fdx", description = "Clean the repository" }

[dependencies]
python = ">=3.12.0,<3.13"

[feature.pre-commit.dependencies]
pre-commit = ">=4.1.0,<5"

[feature.pre-commit.tasks]
pre-commit-install = { cmd = "pre-commit install -f -t pre-commit -t prepare-commit-msg -t commit-msg", description = "Install pre-commit hooks" }
pre-commit-run = { cmd = "pre-commit run --all", description = "Run pre-commit hooks on all repository files" }

[environments]
pre-commit = ["pre-commit"]
