variables:
  ELASTIX_SOURCE_DIR: $(Build.Repository.LocalPath)
  ELASTIX_BINARY_DIR: $(Agent.BuildDirectory)/Elastix-build
      
jobs:
- job: WindowsVcpkg
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      cd /d C:\vcpkg
      git log -1
      git pull
      git log -1
      .\bootstrap-vcpkg.bat
    displayName: git pull vcpkg and bootstrap-vcpkg
  - script: |
      set VCPKG_DEFAULT_TRIPLET=x64-windows
      vcpkg.exe install itk
      vcpkg.exe integrate install
    displayName: vcpkg install itk and integrate
  - script: |
      mkdir "$(ELASTIX_BINARY_DIR)"
    displayName: Make build directories
  - task: CMake@1
    displayName: 'CMake Generate Elastix'
    inputs:
      cmakeArgs: -G "Visual Studio 15 2017 Win64" -T host=x64 -DBUILD_TESTING=ON -DUSE_ALL_COMPONENTS=ON "$(ELASTIX_SOURCE_DIR)" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
      workingDirectory: "$(ELASTIX_BINARY_DIR)"
  - task: MSBuild@1
    displayName: 'MSBuild'
    inputs:
      solution: '$(ELASTIX_BINARY_DIR)/ALL_BUILD.vcxproj'
      configuration: Release
      platform: x64
      msbuildArguments: /p:VcpkgEnabled=true
  - script: | 
      pushd "$(ELASTIX_BINARY_DIR)"
      # We exclude two flaky tests whose output depend on the runtime environment which cause them to fail on Azure
      ctest -C Release -VV -j 2 -E "elastix_run_example_COMPARE_IM|elastix_run_3DCT_lung.MI.bspline.ASGD.001_COMPARE_TP"
      popd
    displayName: 'CTest Elastix'
