#ifndef __elxInstallAllComponents_h
#define __elxInstallAllComponents_h

#include "elxComponentDatabase.h"

/** The CMake generated files contain macros: */
#include "elxMacro.h"

/** The following file, generated by CMake, declares all
 * the InstallComponent functions implemented by the components. */
#include "elxInstallComponentFunctionDeclarations.h"


int InstallAllComponents( elx::ComponentDatabase * _cdb )
{
  int ret = 0;

  /** The following file, generated by CMake, calls the
   * InstallComponent functions of the components. */

  #include "elxInstallComponentFunctionCalls.h"

  /** ret!=0 when something failed. */
  return ret;

} // end InstallAllComponents

#endif // #ifndef __elxInstallAllComponents_h
