name: Build ITK
description: "Clone and build ITK cross-platform with cache"

inputs:
  itk-git-tag:
    required: true
  c-compiler:
    required: true
  cxx-compiler:
    required: true
  cmake-build-type:
    required: true
  vcvars:
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Attempt to restore itk cache
      id: cache_itk
      uses: actions/cache@v3
      with:
        path: |
          ITK-source
          ITK-build
        key: ${{ inputs.itk-git-tag }}-${{ runner.os }}-${{ inputs.cmake-build-type }}

    - name: Set cache flag
      shell: bash
      run: |
        if [ -d "ITK-build" ]; then
          echo "CACHED=true" >> $GITHUB_ENV
        else
          echo "CACHED=false" >> $GITHUB_ENV
        fi

    - name: Clone ITK
      if: env.CACHED == 'false'
      shell: bash
      run: |
        git clone https://github.com/InsightSoftwareConsortium/ITK.git ITK-source
        cd ITK-source
        git checkout ${{ inputs.itk-git-tag }}

    - name: Build ITK (non-Windows)
      if: runner.os != 'Windows' && env.CACHED == 'false'
      shell: bash
      run: |
        mkdir ITK-build
        cd ITK-build
        cmake -DCMAKE_C_COMPILER="${{ inputs.c-compiler }}" \
              -DCMAKE_CXX_COMPILER="${{ inputs.cxx-compiler }}" \
              -DCMAKE_BUILD_TYPE="${{ inputs.cmake-build-type }}" \
              -DBUILD_SHARED_LIBS=OFF \
              -DBUILD_EXAMPLES=OFF \
              -DBUILD_TESTING=OFF \
              -DITK_LEGACY_REMOVE=ON \
              -GNinja ../ITK-source
        ninja

    - name: Build ITK (Windows)
      if: runner.os == 'Windows' && env.CACHED == 'false'
      shell: cmd
      run: |
        call "${{ inputs.vcvars }}"
        mkdir ITK-build
        cd ITK-build
        cmake -DCMAKE_C_COMPILER="${{ inputs.c-compiler }}" ^
              -DCMAKE_CXX_COMPILER="${{ inputs.cxx-compiler }}" ^
              -DCMAKE_BUILD_TYPE="${{ inputs.cmake-build-type }}" ^
              -DBUILD_SHARED_LIBS=OFF ^
              -DBUILD_EXAMPLES=OFF ^
              -DBUILD_TESTING=OFF ^
              -GNinja ../ITK-source
        ninja
