# Elastix version number components.
set(ELASTIX_VERSION_MAJOR "5")
set(ELASTIX_VERSION_MINOR "0")
set(ELASTIX_VERSION_PATCH "1")

set(ELASTIX_VERSION "${ELASTIX_VERSION_MAJOR}.${ELASTIX_VERSION_MINOR}.${ELASTIX_VERSION_PATCH}")